# Generated by Django 4.0.5 on 2022-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('blogcontent', models.TextField(max_length=500, verbose_name='BlogContentmax')),
            ],
        ),
    ]
