# Generated by Django 4.0.5 on 2022-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='blogcontent',
            field=models.TextField(max_length=500, verbose_name='BlogContent'),
        ),
    ]
